###############################
#      OH MY ZSH CONFIG       #
###############################


#Paths
export EDITOR="nvim"
export VISUAL="nvim"
export PATH="/home/$USER/anaconda3/bin:$PATH"
export SDKMAN_DIR="/home/reus/.sdkman"
source $HOME/.sdkman/bin/sdkman-init.sh
source $HOME/.cargo/env
export HISTFILE=~/.zsh_history
export HISTSIZE=10000
export SAVEHIST=10000

nvm() {
   unset -f nvm
   export NVM_DIR=~/.nvm
   [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
   nvm "$@"
}
node() {
   unset -f node
   export NVM_DIR=~/.nvm
   [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
   node "$@"
}
npm() {
   unset -f npm
   export NVM_DIR=~/.nvm
   [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
   npm "$@"
 }


#fpath+=('/home/reus/.nvm/versions/node/v12.9.0/lib/node_modules/pure-prompt/functions')
#autoload -U promptinit; promptinit
#prompt pure

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/reus/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/reus/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/reus/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/reus/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<


alias jcert="java -jar /home/reus/HDD/software/etsviewer.jar"

zstyle ':completion:*' menu select
autoload -U compinit && compinit
_comp_options+=(globdots)

# zplug
source ~/.zplug/init.zsh
zplug "zsh-users/zsh-history-substring-search"
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug load

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=30'

bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down

# Ranger integration
run_ranger () {
    echo
    ranger --choosedir=$HOME/.rangerdir < $TTY
    LASTDIR=`cat $HOME/.rangerdir`
    cd "$LASTDIR"
    zle reset-prompt
}

zle -N ranger run_ranger
# bindkey "^e" ranger


m8s() { sudo microk8s."$@";  }

source /home/reus/.config/broot/launcher/bash/br

fpath=($fpath "/home/reus/.zfunctions")

SPACESHIP_PROMPT_ADD_NEWLINE=false

# Set Spaceship ZSH as a prompt
autoload -U promptinit; promptinit
prompt spaceship
fpath=($fpath "/home/reus/.zfunctions")

